version: '3.8'

services:
  postgres:
    image: postgres
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_DB: task_management
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin@123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
